### ISSUE TITLE
how to bind queue and exchange  with many routing key 

### ISSUE THREAD

**Issue by wdhaoui** [ricbra/rabbitmq-cli-consumer#53]
I can add this configuration in php-amqplib/rabbitmq-bundle:

```yml
old_sound_rabbit_mq:
    connections:
        consumer_connection:
            host: "%rabbitmq_host%"
            port: "%rabbitmq_port%"
            user: "%rabbitmq_user%"
            password: "%rabbitmq_password%"
    consumers:
        log:
            connection: consumer_connection
            exchange_options:
                name: "exchange_log"
                type: direct
            queue_options:
                name: "log"
                routing_keys:
                    - log
                    - userLog
                    - subscriptionLog
```
I want to transform this configuration  into GO configuration, like this
```conf
[rabbitmq]
host = rabbitmq
username = user
password = pass
vhost= /
port= 5672
queue= log
compression= On

[prefetch]
count= 3
global= Off

[exchange]
name=exchange_log
autodelete=Off
type=direct
durable=On

[queuesettings]
routingkey=log
```
but I can not add only one ropting key.

how to bind queue and exchange  with many routing key ?

example:
[queuesettings]
routingkey=[ userLog,  subscriptionLog]
